# Generated by Django 3.2.6 on 2021-12-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totSellamnt', models.IntegerField()),
                ('drwNoDate', models.CharField(max_length=10)),
                ('firstWinamnt', models.IntegerField()),
                ('drwNo', models.IntegerField()),
                ('drwtNo1', models.IntegerField()),
                ('drwtNo2', models.IntegerField()),
                ('drwtNo3', models.IntegerField()),
                ('drwtNo4', models.IntegerField()),
                ('drwtNo5', models.IntegerField()),
                ('drwtNo6', models.IntegerField()),
                ('bnusNo', models.IntegerField()),
                ('firstPrzwnerCo', models.IntegerField()),
                ('returnValue', models.CharField(max_length=20)),
                ('firstAccumamnt', models.IntegerField()),
            ],
        ),
    ]
